### ISSUE TITLE
sass not a function with v1.2.6

### ISSUE THREAD

**Issue by magicink** [elycruz/rollup-plugin-sass#85]
After upgrading from v1.2.4 to v1.2.6, Rollup complains that `sass` is not a function.

The following Rollup config works with v1.2.4

```
const sass = require('rollup-plugin-sass')

module.exports = {
  ...
  plugins: [
    ...
    sass({
      insert: true,
      processor: css =>
        postcss([autoprefixer])
          .process(css, { from: undefined })
          .then(result => result.css),
      runtime: require('sass')
    })
    ...
  ]
}
```

After upgrading:

```
[!] TypeError: sass is not a function
```

This is the `devDependencies` section of my projects `package.json`:

```
  "devDependencies": {
    "rollup": ">=2.56.3",
    ...
    "rollup-plugin-sass": "1.2.6",
    "sass": ">=1.37.5"
  }
```

**Comment by magicink** [comment]
Okay it looks like with v1.2.6 to use this plugin via `require()` you have to manually reference `require('rollup-plugin-sass').default`. Using `import` works as documented.

**Comment by elycruz** [comment]
Fix applied - Plugin module import syntax updated to use typescript's CommonJs compatible default exports (instead of pure 'es6' default exports) - Plugin distribution files now contain previous 'exports' syntax for default export.

(@magicink)
