### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by nathancahill** [elycruz/rollup-plugin-sass#27]
Running `npm run build` after cloning from GitHub:

```bash
$ npm run build
> node build/build.js

node_modules/nan
resolve failed:  { Error: Cannot find module 'babel-runtime'
```

babel-runtime is installed in node_modules.

**Comment by nathancahill** [comment]
Fixed with #28. Also fixes the broken build in #26.
